#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/nextcloud
nextcloud_app_dir: /etc/nextcloud
nextcloud_volumes_dir: /etc/nextcloud/data
nextcloud_port: 8080

nextcloud_db_password:
nextcloud_db_root_password:

nextcloud_docker_compose:
  services:
    db:
      image: mariadb:10.6
      restart: always
      command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
      volumes:
        - "{{ nextcloud_volumes_dir }}/db:/var/lib/mysql"
      environment:
        - MYSQL_ROOT_PASSWORD= "{{ nextcloud_db_root_password }}"
        - MYSQL_PASSWORD= "{{ nextcloud_db_password }}"
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud

    app:
      image: nextcloud
      restart: always
      ports:
        - "{{ nextcloud_port }}:80"
      links:
        - db
      volumes:
        - "{{ nextcloud_volumes_dir }}/nextcloud:/var/www/html"
      environment:
        - MYSQL_PASSWORD= "{{ nextcloud_db_password }}"
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
        - MYSQL_HOST=db
