#SPDX-License-Identifier: MIT-0
---
# handlers file for wireguard-common
- name: Restart WireGuard
  ansible.builtin.systemd:
    name: wg-quick@{{ wg_interface }}
    state: restarted
    daemon_reload: true