all:
  children:
    gateways:
      hosts:
        racknerd-micro-1:
    edges:
      hosts:
        racknerd-micro-1:
    wg_servers:
      hosts:
        racknerd-micro-1:
    wg_clients:
      hosts:
        rpi4:
        immich:
    workers:
      hosts:
        rpi4:
    venv_hosts:
      hosts:
        immich: