#SPDX-License-Identifier: MIT-0
---
# tasks file for wireguard-server
- name: Generate WireGuard configuration from template
  ansible.builtin.template:
    src: "{{ wg_interface }}.conf.j2"
    dest: /etc/wireguard/{{ wg_interface }}.conf
    owner: root
    group: root
    mode: '0600'
  notify: Restart WireGuard

- name: Ensure WireGuard service is enabled and started
  ansible.builtin.systemd:
    name: wg-quick@{{ wg_interface }}
    enabled: true
    state: started