#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/nextcloud
- name: Create Nextcloud directory
  ansible.builtin.file:
    path: "{{ nextcloud_app_dir }}"
    state: directory
    mode: '0755'

- name: Check if docker-compose.yml exists
  ansible.builtin.stat:
    path: "{{ nextcloud_app_dir }}/docker-compose.yml"
  register: compose_file_check

- name: Stop Nextcloud service
  community.docker.docker_compose_v2:
    project_src: "{{ nextcloud_app_dir }}"
    state: stopped
  when: compose_file_check.stat.exists

- name: Generate Docker compose file from template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ nextcloud_app_dir }}/docker-compose.yml"

- name: Start Nextcloud service
  community.docker.docker_compose_v2:
    project_src: "{{ nextcloud_app_dir }}"
    pull: missing
    state: present
