#SPDX-License-Identifier: MIT-0
---
# tasks file for firewall
- name: Setup UFW rules
  become: true
  when: ufw_rules is defined and ufw_rules | length > 0
  ansible.builtin.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ ufw_rules }}"
  notify: Reload UFW

- name: Set UFW state
  ansible.builtin.ufw:
    state: "{{ 'enabled' if ufw_rules is defined and ufw_rules | length > 0 else 'disabled' }}"