#SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Install common system packages
  ansible.builtin.apt:
    name:
      - vim
      - curl
      - htop
    state: present
    update_cache: yes